branch-defaults:
  master:
    environment: MeshBack-dev
    group_suffix: null
environment-defaults:
  MeshBack-dev:
    branch: master
global:
  application_name: MeshBack
  branch: null
  default_ec2_keyname: mesh_rsa
  default_platform: PHP 7.1
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
